### ISSUE TITLE
SwitchOnGameplayAttribute node in AttribteSetManager using custom AttributeSet resets on project restart.

### ISSUE THREAD

**Issue by ItsAlf** [GASCompanion/GASCompanion-Documentation#13]
To reproduce:
1. Create a custom attribute set with the Attribute set creation wizard.
2. Create an AttributeSetManager Blueprint
3. Set your AttributeSetManager and custom Attribute Set in the project settings
4. Place a SwitchOnGameplayAttribute node in the graph of your AttributeSetManager.
4. Add attributes from your custom attribute set to the Switch node.
5. Restart your project. The node will be reset, as shown below:

Before restart:
![image](https://user-images.githubusercontent.com/48450551/116885708-2ff7b700-abf6-11eb-8acd-d59a49350fc0.png)

After Restart:
![image](https://user-images.githubusercontent.com/48450551/116885820-4dc51c00-abf6-11eb-9e95-551508cbe591.png)

**Comment by mklabs** [comment]
Thanks @ItsAlf I'll take a look at that

**Comment by mklabs** [comment]
Should be fixed by GASCompanion/GASCompanion-Plugin@756ff3513e3fafe6690a42514372c8afa23bc0da
