### ISSUE TITLE
Seems Actor not support ModularActor, still use GSCActor which Deprecated.

### ISSUE THREAD

**Issue by shi2hh** [GASCompanion/GASCompanion-Documentation#27]
**Describe the bug**

**To Reproduce**
What did you do?

It is best to reproduce in a blank project (with GAS Companion installed in engine, not project). If possible provide a link to this project either as a github repo or google drive link to a zip file (or similar platforms) and a list of clear reproduction steps.

**Expected behavior**

**Actual behavior**
What happened instead?

**Screenshots**

**Environment (please complete the following information):**
- Engine version: 4.26 / 4.27 / 5.0 early access
- GAS Companion Plugin version: 3.2.0 (please be specific, and try latest release. You can find this information in the Plugins window within the Editor)
- OS: Windows / Mac / Linux

**Additional context**

**Comment by mklabs** [comment]
There is indeed no Modular Actor with support for ASC currently (in v3 and 4.27), only Pawn and Character based.

If you really need it, you can follow this guide: https://gist.github.com/mklabs/305a223866c5f1c506219e2df5781e7e

I made this for another user asking the same question on the marketplace page.

Main reason there is no Actor support right now is that while I want to bring back an Actor based class with ASC, I'd like to implement it with a lazy loaded mechanism and approach, and it'll require a bit more time and research to do right. You may have a lot of these actors around, which for the most part can never be interacted by the player (like taking damage), this is where lazy loading would come handy.

Thank you for opening the issue, I'll keep this in mind for next releases. But it's not on the top of the priority list right now, and won't be until late april.

Next version will be about adding support for confirm / cancel input via Enhanced Input, and after that, preparation for v4 which will remove all deprecated classes and consolidate the code base in preparation for ue5 release.
